FROM golang:1.14 AS builder
WORKDIR /myapp
COPY helloworld.go .
RUN go build -o helloworld .

FROM alpine:latest AS runtime
WORKDIR /myapp
COPY --from=builder /myapp/helloworld .
ENTRYPOINT [ "./helloworld" ]
