apiVersion: v1
kind: Service
metadata:
  name: hostname-service-loadbanacer
spec:
  type: LoadBalancer
  selector:        
    app: webserver
  ports:
  - name: web-port
    port: 8080    
    targetPort: 80
