apiVersion: v1
kind: Service
metadata:
  name: hostname-service-nodeport
spec:
  type: NodePort
  selector:        
    app: webserver
  ports:
  - name: web-port
    port: 8080    
    targetPort: 80
    # nodePort: 31000  # 30000~32768 포트 중 하나를 지정
